---
- name: Deploy Services
  hosts: lab9-vm
  become: no
  tasks:
    - name: Clone/Pull Git Repo
      ansible.builtin.git:
        repo: git@github.com:Pauwo/ACIT3855-Lab9.git
        dest: /home/paulo/lab9
        accept_hostkey: yes
        key_file: ~/.ssh/id_ed25519

    - name: Ensure Docker Compose is Running
      ansible.builtin.shell: |
        cd /home/paulo/lab9
        docker compose up -d --build
      args:
        executable: /bin/bash