---
- name: Deploy Services
  hosts: lab9-vm
  become: no
  tasks:
    - name: Clone/Pull Git Repo
      ansible.builtin.git:
        repo: git@github.com:Pauwo/ACIT3855-Lab9.git
        dest: /home/paulo/lab9
        accept_hostkey: yes
        version: main
        key_file: ~/.ssh/id_ed25519

    - name: Create 'data' and 'logs' directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
        owner: nobody
        group: nogroup
      loop:
        - /home/paulo/lab9/data
        - /home/paulo/lab9/logs
        - /home/paulo/lab9/data/event_stats.json
      become: true

    - name: Copy all files from prod to test
      synchronize:
        src: /home/paulo/acit3855/ACIT3855-Lab9/config/prod/
        dest: /home/paulo/lab9/config/test/
        mode: push  # The push mode is for copying from the local machine to the remote server
        recursive: yes  # Ensure all files and subdirectories are copied
        delete: no 



    - name: Ensure Docker Compose is Running
      ansible.builtin.shell: |
        cd /home/paulo/lab9
        docker compose up -d --build
      args:
        executable: /bin/bash