---
- name: Deploy Services
  hosts: lab9-vm
  become: no
  tasks:
    - name: Clone/Pull Git Repo
      ansible.builtin.git:
        repo: git@github.com:Pauwo/ACIT3855-Lab9.git
        dest: /home/paulo/lab9
        accept_hostkey: yes
        version: main
        key_file: ~/.ssh/id_ed25519

    - name: Create 'data' and 'logs' directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
        owner: nobody
        group: nogroup
      loop:
        - /home/paulo/lab9/data
        - /home/paulo/lab9/logs
      become: true

    - name: Copy contents of config/prod to config/test
      ansible.builtin.copy:
        src: "config/prod/"
        dest: "/home/paulo/lab9/config/test/"
        mode: "0644"
        owner: nobody
        group: nogroup
        remote_src: yes
        recursive: yes

    - name: Ensure Docker Compose is Running
      ansible.builtin.shell: |
        cd /home/paulo/lab9
        docker compose up -d --build
      args:
        executable: /bin/bash